# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24d738337ad14e836069c1039ea938b20efc39679524cda28fa47137990c6b2b19283745fe29862b3ce4d76a813235ad610179b2642860a67d090963841f09b8

test:
  secret_key_base: a4de29e4b3b0a5d1cbebf6d0908c6ee9070b9a2bdb0093ec7cb0f5556c14fa0d701b0a730e6cec7ec528d2fd4153277e87a47cb9acc08ff458e3637ec25425f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
